# Generated by Django 4.2.3 on 2024-06-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueactivity',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_activities', to='landmark.landmark'),
        ),
    ]
