# Generated by Django 4.2.3 on 2024-06-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0003_rename_day_ticketprice_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='history',
        ),
        migrations.CreateModel(
            name='LandmarkContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='landmark.landmark')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='landmark.language')),
            ],
        ),
    ]
