  services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: some_password
        POSTGRES_DB: educa_tour
      ports:
        - "5432:5432"

    web:
      image: ferryhusnil/ce_tour
      environment:
        - ENVIRONMENT=production
        - DATABASE_URL=postgres://postgres:some_password@postgres:5432/educa_tour
        - SECRET_KEY=some_secret
      volumes:
        - ./staticfiles:/app/staticfiles
      expose:
        - "8000"
      depends_on:
        - postgres
      restart: always

    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./staticfiles:/app/staticfiles
      depends_on:
        - web