name: Publish and Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.IMAGE_NAME}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          IMAGE_NAME: ${{secrets.IMAGE_NAME}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          ENVIRONMENT: production
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          envs: DOCKERHUB_USERNAME,IMAGE_NAME,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,SECRET_KEY,ENVIRONMENT
          script: |
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export IMAGE_NAME=$IMAGE_NAME
            export POSTGRES_USER=$POSTGRES_USER
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            export POSTGRES_DB=$POSTGRES_DB
            export SECRET_KEY=$SECRET_KEY
            export ENVIRONMENT=$ENVIRONMENT

            newgrp docker
            docker rm -f $(docker ps -a -q)
            docker rmi -f $(docker images -q)
            cd ~/CeTour
            docker compose up --build -d
